### ISSUE TITLE
Use custom exception for injecting container into object with unknown dependencies

### ISSUE THREAD

**Issue by asvetlov** [tailhook/injections#5]
I have a class
```
@has
class A:
    redis = depends(Redis)
    loop = depends(AbstractLoop)
```

When I try to initialize it from container with missing dependencies I have a `KeyError`.
```
inj = Container()
inj['redis'] = create_redis()
inj.inject(A())  # raises KeyError
```

Exception on injection stage is pretty cool but I suggest using custom exception class. Not `KeyError` but derived from it. Exception text also should be more informative than just `KeyError: 'loop'`.

**Comment by tailhook** [comment]
Agree with all said. Do you want to provide a pull request?

**Comment by asvetlov** [comment]
Looks like I should :)
